version: "3.9"

services:
  api:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: realestate
    ports:
      - "5432:5432"
