name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker
      run: docker build -t realestate-app .

    - name: Deploy
      run: echo "Deploy to server via SSH (EC2)"
